---
title: "&nbsp;"
output: 
  html_document:
    number_sections: false
    toc: false    
    css: theme.css
---

```{r prepare, echo=FALSE, message=FALSE, warning=FALSE}
library(flextable)
library(dplyr)
library(dlookr)
library(ggplot2)

id_dataset <- "dataset-85343be57e"
method <- "pearson"
alternative <- "two.sided"
variables <- "carat,table"
group_flag <- TRUE
group_variable <- "cut,color"
plot_flag <- TRUE  
```

```{r title-matrix, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
htmltools::h3(
  BitStat::translate("상관검정")
)
```

```{r content-matrix, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
.data <- get("list_datasets", envir = .BitStatEnv) %>% 
  "[["(id_dataset) %>% 
  "[["("dataset")
  
formula <- variables %>% 
  stringr::str_replace_all("^|$", "`") %>% 
  stringr::str_replace(",", "`,`") %>% 
  strsplit(",") %>% 
  unlist() %>% 
  paste(sep = "`", collapse = " + ") %>% 
  paste("~", .)
  
if (!group_flag) {
  cor.test(formula = as.formula(formula), data = .data, method = method, 
           alternative = alternative) %>% 
    asis_test()
} else {
  cases <- group_variable %>% 
  strsplit(",") %>% 
  unlist() %>% 
    purrr::map(
      function(x) {
        levels(.data[[x]])
      }
    ) %>% 
    expand.grid()
    
  group_variable <- group_variable %>% 
  strsplit(",") %>% 
  unlist()
    
  names(cases) <- group_variable
  
  cases %>% 
    NROW() %>% 
    seq() %>% 
    purrr::walk(
      function(x) {
        condition <- cases[x, ] %>% unlist()
        labs <- paste(names(condition), condition, sep = "=", collapse = ", ")
          
        data_sub <- cases[x, ] %>% 
          inner_join(
            .data %>% 
              # select(all_of(group_variable)) %>% 
              mutate_at(vars(all_of(group_variable)), as.character),
            by = cases %>% names()
          ) 
        
        htmltools::h4(labs)
        
        tryCatch(
          cor.test(formula = as.formula(formula), data = data_sub, method = method, 
                   alternative = alternative) %>% 
            asis_test(),
          error = function(e) {
            message <- BitStat::translate(e$message, msg_language = "en")
            cat(htmltools::h5(message) %>% as.character())
          },
          finally = NULL
        )
        }
    )
}


```

```{r title-plot, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
if (plot_flag) {
  htmltools::h3(
    BitStat::translate("상관관계 플롯")
  )
}
```

```{r content-plot, echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', out.width='75%'}
if (plot_flag) {
variables <- variables %>% 
  stringr::str_replace_all("^|$", "`") %>% 
  stringr::str_replace(",", "`,`") %>% 
  strsplit(",") %>% 
  unlist()

.data %>% 
  ggplot(aes_string(x = variables[1], y = variables[2])) +
  geom_point() +
  geom_smooth(formula = "y ~ x", method = "lm", se = FALSE) +
  labs(title = translate("두 변수의 상관관계")) +
  hrbrthemes::theme_ipsum(base_family = "NanumSquare")

}
```

