---
title: "&nbsp;"
output: 
  html_document:
    number_sections: false
    toc: false    
    css: theme.css
---

```{r prepare, echo=FALSE, message=FALSE, warning=FALSE}
library(flextable)
library(dplyr)
library(dlookr)

id_dataset <- "$id_dataset$"
variables <- "$variables$"
plot_flag <- $plot_flag$  
```

```{r title-summary-category, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
htmltools::h3(
  BitStat::translate("범주형 변수 집계 테이블")
)
```

```{r content-summary-category, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
.data <- get("list_datasets", envir = .BitStatEnv) %>% 
  "[["(id_dataset) %>% 
  "[["("dataset")
  
if (!variables[1] %in% "") {
  variables <- variables %>% 
  strsplit(",") %>% 
  unlist() 
}

if (!variables[1] %in% "") {  
  summ_category <- .data %>% 
    select(all_of(variables)) %>% 
    dlookr::univar_category()     
} else {
  summ_category <- .data %>% 
    dlookr::univar_category()     
}  

length(summ_category) %>% 
  seq() %>% 
  purrr::walk(
    function(x) {
      variable <- names(summ_category)[x]
      htmltools::h4(
        translate(glue::glue("{variable}의 분포 현황"), "kr", variable)
      ) %>% 
        as.character() %>%
        cat()  
      
      summ_category[[x]] %>% 
        mutate(rate = rate * 100) %>% 
        rename(percent = rate) %>% 
        flextable::flextable() %>%
        flextable::colformat_double(digits = 2) %>% 
        flextable::set_caption(caption = translate("돗수분포표")) %>% 
        flextable::theme_booktabs() %>% 
        flextable::flextable_to_rmd()
      
      html_br()
    }
  )

```

```{r title-plot-category, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
if (plot_flag) {
  htmltools::br()
  
  htmltools::h3(
    BitStat::translate("범주형 변수 플롯")
  )
}
```

```{r content-plot-category, echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', out.width='75%', results='asis'}
if (plot_flag) {
  if (variables[1] %in% "") {  
    variables <- dlookr::find_class(.data, type = "numeric", index = FALSE)   
  } 
  
  if (!group_flag) {
    variables %>% 
      purrr::walk(
        function(variable) {
          htmltools::h4(
            translate(glue::glue("{variable}의 분포 현황"), "kr", variable)
          ) %>% 
            as.character() %>%
            cat()  
          
          p <- .data %>% 
            ggplot(aes_string(x = variable)) +
            geom_density() +
            labs(title = translate(glue::glue("{variable}의 분포 현황"), "kr", variable)) +
            hrbrthemes::theme_ipsum(base_family = "NanumSquare")
          
          print(p)
        }
      )
  } else {
    if (length(group_variable) > 1) {
      expand_variable <- group_variable[-1]
      
      cases <- .data %>% 
        select(all_of(expand_variable)) %>%
        unique()
      
      group_variable <- group_variable[1]
    } else {
      cases <- NULL
    }
    
    variables %>% 
      purrr::walk(
        function(variable) {
          htmltools::h4(
            translate(glue::glue("{variable}의 분포 현황"), "kr", variable)
          ) %>% 
            as.character() %>%
            cat()  
          
          if (is.null(cases)) {
            p <- .data %>% 
              ggplot(aes_string(x = variable, y = group_variable, group = group_variable)) +
              geom_density_ridges(fill = "steelblue", alpha = 0.5) +
              labs(title = translate(glue::glue("{variable}의 분포 현황"), "kr", variable)) +
              hrbrthemes::theme_ipsum(base_family = "NanumSquare")
          
            print(p)
          } else {
            cases %>% 
              NROW() %>% 
              seq() %>% 
              purrr::walk(
                function(x) {
                  condition <- cases[x, , drop=FALSE] %>% unlist()
                  labs <- paste(names(condition), condition, sep = "=", collapse = ", ")
                    
                  data_sub <- cases[x, , drop=FALSE] %>% 
                    inner_join(
                      .data %>% 
                        mutate_at(vars(all_of(group_variable)), as.character),
                      by = cases %>% names()
                    ) 
                  
                  htmltools::h5(labs) %>% 
                    as.character() %>% 
                    cat()          
                  
                  p <- data_sub %>% 
                  ggplot(aes_string(x = variable, y = group_variable, group = group_variable)) +
                  geom_density_ridges(fill = "steelblue", alpha = 0.5) +
                  labs(title = translate(glue::glue("{variable}의 분포 현황"), "kr", variable),
                       subtitle = labs) +
                  hrbrthemes::theme_ipsum(base_family = "NanumSquare")
              
                print(p)
                }
              )  
          }      
        }
      )    
  }  
}
```

